config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if(@todo.save)
      redirect_to todos_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to todos_path
    else
      render :edit
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<div class="container">
  <h1>タスクの編集</h1>

<%= form_with model: @todo do |form| %>
  <%= form.text_field :title, placeholder:"タスクを入力する" %>
  <%= form.submit "変更する" %>
<% end %>
</div>

app/views/todos/index.html.erb
<div class="container">
  <h1>Todo List</h1>
  <%= link_to 'タスクを追加する', new_todo_path, class: 'new-task' %>
  <table>
    <thead>
      <tr>
        <th>タスク</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>
      <!-- ここは後から動的コンテンツに置き換える -->
      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.title %></td>
          <td>
            <%= link_to '編集', edit_todo_path(todo.id), class: 'edit' %>
            <%= link_to '削除', todo_path(todo.id), data: { turbo_method: :delete } , class: 'delete' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/todos/new.html.erb
<div class="container">
  <h1>タスクの追加</h1>
  <% if @todo.errors.any? %>
    <div  class="alert">
      <p>タスクのタイトルを入力してください</p>
    </div>
  <% end %>
  <%= form_with model: @todo do |form| %>
    <div class="form-group">
      <%= form.text_field :title, placeholder:"タスクを入力する" %>
      <%= form.submit "保存する" %>
    </div>
  <% end %>
</div>